### ISSUE TITLE
packages exclude for reposync

### ISSUE THREAD

**Issue by fuco809** [pnasrat/yum-utils#3]
is it possible to add an option like exclude=kde\* on reposync to filter one or multiple packages from the downloadlist before fetching them. i need to reduce the repository size (no need for gui) of the synced rhel repo.

**Comment by pnasrat** [comment]
Note this is a clone of the main repository and I am not an upstream maintainer - you probably want to 

https://bugzilla.redhat.com/ or http://lists.baseurl.org/mailman/listinfo/yum-devel to discuss features

**Comment by fuco809** [comment]
sorry and thanks

**Comment by pnasrat** [comment]
No worries. As it happens I have time today and may be able to provide a
patch and try get it upsteramed. Give me a few hours

**Comment by pnasrat** [comment]
To do this it'd be handy to know - what precise version of yum-utils you are using on what distro.

**Comment by fuco809** [comment]
hi, i tried a simple quick and dirty workaround in the code of reposync and it works for me.

```
       # Disable cache otherwise things won't download
        repo.cache = 0
        if not opts.quiet:
            my.logger.info( '[%s: %-5d of %-5d ] Downloading %s' % (repo.id, n, len(download_list), remote))
        pkg.localpath = local # Hack: to set the localpath we want.
        # quick and dirty filtering of exclude list
        if pkg.name.startswith(('kde','gnome','xorg','libreoffice-langpack','rhel-guest-image','qt-doc','texlive-texmf','gimp','firefox','eclipse','qt-x11','wireshark','oxygen','scenery')):
            my.logger.info( 'this packages is EXCLUDED')
            continue
        try:
            path = repo.getPackage(pkg)
```

my yum-utils version are: 1.1.30 (yum-utils-1.1.30-30.el6.noarch on rhel6)
